- job:
    name: myjob1
    description: My custom job
    run: myjob1.yaml
- project:
    check:
      jobs:
        - myjob1
        - noop
       
    gate:
      jobs:
        - myjob1
        - noop
